# Ejercicio de comprobación



**Objetivos**

- Crear entonrno virtual.
- Familiarizarse con Jupyter Notebook y Markdown.
- Practicar las funcionalidades básicas de GitHub.

---

In [2]:
import pandas as pd
import numpy as np

## 1. Operaciones

In [3]:
8-5

3

In [4]:
10-2

8

In [5]:
8**2

64

In [6]:
#Ejemplo de vector con Numpy
np.array([1,2,3])

array([1, 2, 3])

In [7]:
#Ejemplo de array multidimensional con Numpy
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
#Ordenar
v = np.random.rand(10)
print(v)

[0.04414113 0.61058732 0.01596829 0.52939857 0.45929777 0.7499897
 0.8511447  0.31534286 0.12341782 0.13341976]


In [9]:
#Estadísticos
v = np.arange(20)
print(v.mean())
print(np.median(v))
print(np.std(v))
print(v.var())
print(v.max())
print(v.min())
print(np.corrcoef(v,v))

9.5
9.5
5.766281297335398
33.25
19
0
[[1. 1.]
 [1. 1.]]


In [10]:
#Listas
alumnos = ['Juan', 'Pedro', 'María', 'Marta']
alumnos

['Juan', 'Pedro', 'María', 'Marta']

## 2. Crear títulos, listas, cambiar el estilo de la letra o agregar imágenes dentro del Notebook.

### 2.1 Crear Títulos

# Título de Nivel 1
## Título de Nivel 2
### Título de Nivel 3

### 2.2 Crear Listas

1. Primer elemento
2. Segundo elemento
   1. Subelemento 2.1
   2. Subelemento 2.2


### 2.3 Cambiar el Estilo de la Letra

- Negrita: Usar **texto** o __texto__
- Cursiva: Usar *texto* o _texto_
- Tachado: Usar ~~texto~~

### 2.4 Agregar Imágenes

![Terminal](Screenshot_2024-09-20_203239.png)